abhpd/hacktoberfest2021

Java/Projects/Actualtime.java

That's the same program I've Pull Requested, but now on the correct folder.

Added Actualtime.java (now in Projects folder)

---

C/Operating System Algos/First Come First Serve.c
C/Operating System Algos/Round Robin.c
C/Operating System Algos/Shortest job first.c

-Simple CPU Scheduling Algo's using Struct to define properties of a process
-Auto-select 0 for arrival times
-Uses rand function to generate pseudo-random integer based on time.This is used for process ID

CPU Scheduling Algos

---

C++/Algorithms/Dyanmic Programming/MinJumps_DP.cpp

Added a DP program in C++ file for Hacktoberfest pls review and merge :-)

Added DP folder and a DP program

---

C++/Algorithms/Recursion/ReduceToOne.cpp

Title: Recursion in c++
This program will reduce the given number to 1 in minimum number of steps.

ReduceToOne.cpp - Recursion

---

C/Algorithms/Sorting/QuickSort_Random.c

This pull request will add a code of Quick Sort (Randomized version) in C. This code is tested on an array of 10,000 elements and has the necessary comments in it

Adding QuickSort Randomized Version in C

---

C++/DataStructures/SinglyLinkedList.cpp
C++/DataStructures/SinglyLinkedList.h
C/Algorithms/Sorting/QuickSort_Random.c

This pull request will create a new folder "Data Structures" inside C++ and will add two files i.e implementation of Singly Linked List's header and code.

Adding Linked List C++

---

Javascript/Algorithms/Sorting/Insertion-Sort/insertionSort.js

Add Insertion Sort Algorithm in Javascript

---

C++/Algorithms/Recursion/AllIndexs.cpp

Finds A Indexes of a particular number, and returns it into an output array with the help of Recursion.

AllIndexes

---

C++/Algorithms/Recursion/RecursionMultiply.cpp

Multiplies 2 number recursively.

RecursionMultiply

---

C++/Algorithms/Dyanmic Programming/EditDistance.cpp
C++/Algorithms/Dyanmic Programming/ShortestSubsequence.cpp

Added two DP Problems - 
1. Edit Distance
2. Shortest Subsequence

DP Problems

---

Javascript/Data-structures/Hash-Table/stacks.js

Stacks in JavaScript are added to check for balanced parentheses

Added stack implemenattion in JS

---

C++/DataStructures/Circular-Queue.cpp

added all functionalities in it.
please tag hacktoberfest-accepted label if you find this useful

Added circular queue in data structures in cpp language

---

Java/A very big sum.java
Java/Projects/A very big sum.java

In this prog., we are required to calculate and print the sum of the elements in an array, keeping in mind that some of those integers may be quite large.

A very Big Sum

---

Java/Algorithms/Sorting/SelectionSort/SelectionSort.java

Selection sort made with Java! This sort selects from the lowest number on the array! :smiley:

Added SelectionSort.java

---

Python/Algorithm/Sorting/Bubble_sort.py
Python/Algorithm/Sorting/Selection_sort.py

Added python sorting algorithms

sorting algorithms

---

C++/Algorithms/Dyanmic Programming/MinimumCount.cpp

Given an integer N, find and return the count of minimum numbers required to represent N as a sum of squares.

Minimum Count

---

Java/Projects/Plus Minus.java

In an array of integers, we're calculating the ratios of its elements that are positive, negative, and zero. Also, printing the decimal value of each fraction on a new line with 6  places after the decimal.

Plus Minus Problem

---

Java/Projects/ThreadPoolPerformance.java

This is the thread pool project I am studying recently

ThreadPoolPerformance

---

C++/DataStructures/Queue using Stacks.cpp

Queue using Stacks.cpp

---

C++/DataStructures/tree traversal.cpp

tree data struture(tree taversal)

tree traversal.cpp

---

C++/Data Structure/n_queens_problem.cpp

Here is a cpp program for N Queens problem in data structures

added new cpp file for n_queens_problem

---

C++/Algorithms/Searching/Jump Search.cpp

comment added,thanks for fast reply

Jump Search.cpp

---

C++/Problems/backtracking/A*_weels.cpp

Create Problems folder in C++ folder and add a solved problem. The problem description is in the program's first comment.

Create C++/Problems folder and add a problem

---

C++/Algorithms/Tree Algorithms/find_lowest_common_ancestor_bst.cpp

CPP Code to find LCA of two nodes in a BST

Created find_lowest_common_ancestor_bst.cpp

---

C++/Algorithms/Graph Theory Algorithms/bfs_rotten_oranges.cpp
C++/Algorithms/Searching/search_element_in_row_column_sorted_matrix.cpp

C++ code to find minimum time required to make all oranges rotten using Breadth first Search Algorithm

Created bfs_rotten_oranges.cpp

---

C++/Algorithms/Dyanmic Programming/Longest Common Subsequence.cpp

C++ program to find out the length of the longest common subsequence using dynamic programming.

Created Longest Common Subsequence.cpp

---

C++/Algorithms/Dyanmic Programming/coinchange.cpp

added coinchange problem of dynamic programming in algorithms folder of c++. please merge if possible

added coinchange.cpp

---

C++/Algorithms/Greedy/slidingWindowMAximum.cpp

Code for sliding window maximum problem is added with approriate complextiy analysis.

Added sliding window maximum problem

---

C++/DataStructures/stocks_Buy_And_Sell_Problem.cpp

Array - Cpp
Added a new program to find the maximum profit from the give stocks prises

Stocks Buy and Sell Problem

---

Python/Algorithms/rabin karp algorithm.py

Rabin-Karp String Matching Algorithm in python.
easy to understand.
very important.

Create rabin karp algorithm.py

---

Python/Projects/TicTacToe/tictactoe.py

A simple tictactoe game
Easy to understand for beginners

tictactoe game

---

C++/DataStructures/colouring_binary_tree.cpp

@abhpd Kindly review my Pull request for Hacktoberfest 2021.
Thank you

Colouring binary tree code added

---

Java/Algorithms/Sorting/CountSort/CSorting.java

Count Sort in JAVA is added!
This PR includes :
1-What is Count Sorting?
2-How it is done?
3-Code in JAVA.

Count Sorting in Java added

---

Java/Algorithms/Sorting/BucketSort/BucketSort.java

Hey! I have added BucketSort Algorithm .
Please Review my request.
Thank You!

Implemented Bucket Sort Algorithm in Java

---

Java/Algorithms/Sorting/HeapSort/HeapSort.java

added a heap sort algorithm in java folder under the algorithm-> sorting.
please approve and merge.
Hacktoberfest'21

added a heap sort algorithm

---

Java/Algorithms/Graphs/Dijkstra.java

Dijkstra's Algorithm to find the shortest path between nodes of a weighted acyclic and directed graph. Uses extensive OOPs and also returns the shortest path between the nodes.

Created Dijkstra's Algorithm in Java

---

Java/Algorithms/Graphs/BellmanFord.java
Java/Algorithms/Sorting/BucketSort.java

Bellman ford implementation in java

BellmanFord.java

---

Java/Algorithms/Sorting/BubbleSortRecursive/BubbleSortRecursive.java

[X] Add bubble sort recursive method.

feat(Java): Add bubble sort recursive method.
